"""Milestone M2 — the rotation math, on synthetic gravity, before Blender.

The handoff calls the OpenCV<->Blender basis conversion and the yaw correction
the most likely place for a sign error, so this file exists to make a sign
error fail here rather than as a scene that looks subtly wrong in a viewport.

Nothing in this file imports bpy. Everything is closed-form.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from photo3d import coords

DOWN_IN_CAMERA = np.array([0.0, 1.0, 0.0])   # +y is down in OpenCV camera coords
DOWN_IN_WORLD = np.array([0.0, 0.0, -1.0])


# ---------------------------------------------------------------------------
# the device -> camera axis map
# ---------------------------------------------------------------------------

# Hand-derived, NOT generated by the code under test. A level camera reads a
# different accelerometer vector in each of the four ways you can hold the
# phone, and all four have to mean "down is straight down in the image".
LEVEL_CAMERA_BY_ORIENTATION = {
    1: [-1.0, 0.0, 0.0],   # landscape, home button right -> device -X is down
    3: [1.0, 0.0, 0.0],    # landscape, home button left  -> device +X is down
    6: [0.0, -1.0, 0.0],   # portrait, top edge up        -> device -Y is down
    8: [0.0, 1.0, 0.0],    # portrait, top edge down      -> device +Y is down
}


@pytest.mark.parametrize("orientation,g_device", sorted(LEVEL_CAMERA_BY_ORIENTATION.items()))
def test_level_camera_reads_level_in_every_orientation(orientation, g_device):
    g_cam = coords.gravity_device_to_camera(g_device, orientation)
    np.testing.assert_allclose(g_cam, DOWN_IN_CAMERA, atol=1e-12)

    pitch, roll = coords.pitch_roll_from_gravity(g_cam)
    assert pitch == pytest.approx(0.0, abs=1e-9)
    assert roll == pytest.approx(0.0, abs=1e-9)


def test_orientation_map_is_a_proper_rotation():
    """A mirrored map would flip handedness and silently invert roll."""
    for orientation, matrix in coords._DEVICE_TO_CAMERA.items():
        assert np.linalg.det(matrix) == pytest.approx(1.0), orientation
        np.testing.assert_allclose(matrix @ matrix.T, np.eye(3), atol=1e-12)


def test_mirrored_orientations_are_refused():
    """2/4/5/7 flip handedness. A rear camera never produces them, and quietly
    treating one as its non-mirrored twin would invert roll with no symptom."""
    for orientation in (2, 4, 5, 7):
        with pytest.raises(coords.CoordinateError):
            coords.gravity_device_to_camera([0.0, -1.0, 0.0], orientation)


@pytest.mark.parametrize("orientation", [1, 3, 6, 8])
def test_device_camera_round_trip(orientation):
    g_cam = coords.gravity_from_pitch_roll(12.0, -7.0)
    back = coords.gravity_device_to_camera(
        coords.gravity_camera_to_device(g_cam, orientation), orientation)
    np.testing.assert_allclose(back, g_cam, atol=1e-12)


# ---------------------------------------------------------------------------
# gravity <-> pitch/roll
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("pitch", [-80.0, -33.0, -1.0, 0.0, 3.3, 45.0, 80.0])
@pytest.mark.parametrize("roll", [-170.0, -90.0, -0.7, 0.0, 0.7, 90.0, 179.0])
def test_pitch_roll_round_trip(pitch, roll):
    g = coords.gravity_from_pitch_roll(pitch, roll)
    assert np.linalg.norm(g) == pytest.approx(1.0)
    back_pitch, back_roll = coords.pitch_roll_from_gravity(g)
    assert back_pitch == pytest.approx(pitch, abs=1e-9)
    assert back_roll == pytest.approx(roll, abs=1e-9)


def test_pitch_sign_is_up_positive():
    """Camera tilted up -> gravity acquires a backward (-z) component."""
    assert coords.gravity_from_pitch_roll(30.0, 0.0)[2] < 0
    pitch, _ = coords.pitch_roll_from_gravity([0.0, math.cos(math.radians(30)),
                                               -math.sin(math.radians(30))])
    assert pitch == pytest.approx(30.0)


def test_roll_sign_leans_world_up_to_the_right():
    """Positive roll must put the world's up direction to the RIGHT of image-up.

    In camera coords, up-in-world is -gravity, and +x is image-right. So a
    positive roll needs a positive x component on -g, i.e. a negative g_x.
    """
    g = coords.gravity_from_pitch_roll(0.0, 20.0)
    up_in_camera = -g
    assert up_in_camera[0] > 0


# ---------------------------------------------------------------------------
# the full camera-to-world rotation
# ---------------------------------------------------------------------------

POSES = [(p, r, h) for p in (-40.0, -5.0, 0.0, 3.3, 60.0)
         for r in (-25.0, 0.0, 0.7, 95.0)
         for h in (0.0, 76.944, 180.0, 271.5)]


@pytest.mark.parametrize("pitch,roll,heading", POSES)
def test_rotation_is_orthonormal_and_right_handed(pitch, roll, heading):
    R = coords.rotation_from_gravity(coords.gravity_from_pitch_roll(pitch, roll), heading)
    np.testing.assert_allclose(R @ R.T, np.eye(3), atol=1e-12)
    assert np.linalg.det(R) == pytest.approx(1.0)


@pytest.mark.parametrize("pitch,roll,heading", POSES)
def test_rotation_puts_gravity_down(pitch, roll, heading):
    """The defining property: whatever the camera was doing, gravity ends up
    pointing at the floor of the Blender scene."""
    g = coords.gravity_from_pitch_roll(pitch, roll)
    R = coords.rotation_from_gravity(g, heading)
    np.testing.assert_allclose(R @ g, DOWN_IN_WORLD, atol=1e-9)


@pytest.mark.parametrize("pitch,roll,heading", POSES)
def test_optical_axis_points_at_the_compass_heading(pitch, roll, heading):
    """The other defining property: the lens faces where the compass said."""
    R = coords.rotation_from_gravity(coords.gravity_from_pitch_roll(pitch, roll), heading)
    forward = R @ np.array([0.0, 0.0, 1.0])
    assert coords.azimuth_deg(forward) == pytest.approx(heading % 360.0, abs=1e-6)
    assert math.degrees(math.asin(np.clip(forward[2], -1, 1))) == pytest.approx(pitch, abs=1e-9)


def test_level_north_facing_camera_is_the_identity_pose():
    """Pinned by hand so the whole family cannot rotate together unnoticed."""
    R = coords.rotation_from_gravity([0.0, 1.0, 0.0], heading_deg=0.0)
    np.testing.assert_allclose(R @ np.array([1.0, 0.0, 0.0]), [1.0, 0.0, 0.0], atol=1e-12)
    np.testing.assert_allclose(R @ np.array([0.0, 1.0, 0.0]), [0.0, 0.0, -1.0], atol=1e-12)
    np.testing.assert_allclose(R @ np.array([0.0, 0.0, 1.0]), [0.0, 1.0, 0.0], atol=1e-12)


def test_east_facing_camera_looks_east():
    R = coords.rotation_from_gravity([0.0, 1.0, 0.0], heading_deg=90.0)
    np.testing.assert_allclose(R @ np.array([0.0, 0.0, 1.0]), [1.0, 0.0, 0.0], atol=1e-12)


def test_near_nadir_camera_still_produces_a_valid_rotation():
    """Pointing straight down leaves the optical axis with no bearing. The
    fallback branch must still return a usable rotation rather than blowing up
    on a zero-length cross product."""
    R = coords.rotation_from_gravity(coords.gravity_from_pitch_roll(-89.995, 0.0), 76.944)
    np.testing.assert_allclose(R @ R.T, np.eye(3), atol=1e-9)
    assert np.linalg.det(R) == pytest.approx(1.0)


# ---------------------------------------------------------------------------
# the Blender camera object matrix
# ---------------------------------------------------------------------------

def test_blender_camera_looks_along_negative_z():
    """Blender cameras look down local -Z with +Y up, OpenCV looks along +Z
    with +Y down. Getting CV_TO_BL backwards gives a camera facing 180 degrees
    the wrong way, which reads as 'the compass is broken'."""
    M = coords.camera_matrix([0.0, 1.0, 0.0], heading_deg=0.0, height_m=1.6)
    R = M[:3, :3]
    np.testing.assert_allclose(R @ np.array([0.0, 0.0, -1.0]), [0.0, 1.0, 0.0], atol=1e-12)
    np.testing.assert_allclose(R @ np.array([0.0, 1.0, 0.0]), [0.0, 0.0, 1.0], atol=1e-12)
    np.testing.assert_allclose(R @ np.array([1.0, 0.0, 0.0]), [1.0, 0.0, 0.0], atol=1e-12)
    np.testing.assert_allclose(M[:3, 3], [0.0, 0.0, 1.6])


def test_blender_camera_matrix_stays_a_rotation():
    for pitch, roll, heading in POSES:
        R = coords.camera_matrix(coords.gravity_from_pitch_roll(pitch, roll),
                                 heading, 1.6)[:3, :3]
        assert np.linalg.det(R) == pytest.approx(1.0)
        np.testing.assert_allclose(R @ R.T, np.eye(3), atol=1e-12)


# ---------------------------------------------------------------------------
# the sun
# ---------------------------------------------------------------------------

def test_sun_direction_matches_compass_convention():
    """Sun azimuth and GPSImgDirection have to mean the same thing, or CG
    shadows fall in a different direction from the real ones."""
    np.testing.assert_allclose(coords.sun_direction(0.0, 0.0), [0, 1, 0], atol=1e-12)
    np.testing.assert_allclose(coords.sun_direction(90.0, 0.0), [1, 0, 0], atol=1e-12)
    np.testing.assert_allclose(coords.sun_direction(180.0, 0.0), [0, -1, 0], atol=1e-12)
    np.testing.assert_allclose(coords.sun_direction(0.0, 90.0), [0, 0, 1], atol=1e-12)
    assert coords.azimuth_deg(coords.sun_direction(76.944, 33.0)) == pytest.approx(76.944)


def test_camera_and_sun_agree_on_where_north_is():
    """A camera facing the sun must see it in the middle of frame. This is the
    one test that would catch the two conventions being independently correct
    but rotated relative to each other."""
    azimuth, elevation = 76.944, 20.0
    g = coords.gravity_from_pitch_roll(elevation, 0.0)
    R = coords.rotation_from_gravity(g, azimuth)
    sun_in_camera = R.T @ coords.sun_direction(azimuth, elevation)
    np.testing.assert_allclose(sun_in_camera, [0.0, 0.0, 1.0], atol=1e-9)
